name: Execute automated checks
on:
  - push
jobs:
# https://github.com/golangci/golangci-lint-action#how-to-use
  go-lint:
    name: Lint go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.21.7'
      - name: Lint go code with golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: v1.64.8
  go-test:
    name: Verify go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.21.7'
      - name: Print go version
        run: go version
      - name: Execute go tests 
        run: go test -v ./...
  tilt-ci-dev:
    name: Verify tilt ci (development images)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      - name: Install tilt cli
        uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c # v0.13.5
        with:
          setup-tools: |
            tilt
          tilt: 'v0.37.2'
      - name: Verify tilt ci
        run: |
          timeout 360 tilt ci
  tilt-ci-prod:
    name: Verify tilt ci (production images)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      - name: Install tilt cli
        uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c # v0.13.5
        with:
          setup-tools: |
            tilt
          tilt: 'v0.37.2'
      - name: Verify tilt ci
        run: |
          PROD=1 timeout 360 tilt ci
